//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalSatisAgi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAMMADDE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HAMMADDE()
        {
            this.URUN = new HashSet<URUN>();
        }
    
        public int hammadde_id { get; set; }
        public string hammadde_ad { get; set; }
        public Nullable<int> hammadde_stok { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<URUN> URUN { get; set; }
    }
}
