//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalSatisAgi.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbSatisEntities1 : DbContext
    {
        public DbSatisEntities1()
            : base("name=DbSatisEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAKIM> BAKIM { get; set; }
        public virtual DbSet<HAMMADDE> HAMMADDE { get; set; }
        public virtual DbSet<SEPET> SEPET { get; set; }
        public virtual DbSet<SIPARIS> SIPARIS { get; set; }
        public virtual DbSet<SIPARIS_K> SIPARIS_K { get; set; }
        public virtual DbSet<URUN> URUN { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<YETKI> YETKI { get; set; }
    }
}
