//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalSatisAgi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEPET
    {
        public int sepet_id { get; set; }
        public Nullable<int> sepet_user_id { get; set; }
        public Nullable<int> sepet_urun_id { get; set; }
        public Nullable<int> sepet_adet { get; set; }
        public Nullable<decimal> sepet_tutar { get; set; }
    
        public virtual URUN URUN { get; set; }
        public virtual USER USER { get; set; }
    }
}
