//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalSatisAgi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPARIS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIPARIS()
        {
            this.SIPARIS_K = new HashSet<SIPARIS_K>();
        }
    
        public int siparis_id { get; set; }
        public string siparis_ad { get; set; }
        public string siparis_soyad { get; set; }
        public Nullable<int> siparis_user_id { get; set; }
        public string siparis_telefon { get; set; }
        public string siparis_adres { get; set; }
        public string siparis_tc { get; set; }
        public Nullable<System.DateTime> siparis_tarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPARIS_K> SIPARIS_K { get; set; }
        public virtual USER USER { get; set; }
    }
}
