//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalSatisAgi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPARIS_K
    {
        public int siparis_k_id { get; set; }
        public Nullable<int> siparis_k_siparis_id { get; set; }
        public Nullable<int> siparis_k_urun_id { get; set; }
        public Nullable<int> siparis_adet { get; set; }
        public Nullable<decimal> siparis_tutar { get; set; }
    
        public virtual SIPARIS SIPARIS { get; set; }
        public virtual URUN URUN { get; set; }
    }
}
