//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalSatisAgi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public URUN()
        {
            this.SEPET = new HashSet<SEPET>();
            this.SIPARIS_K = new HashSet<SIPARIS_K>();
        }
    
        public int urun_id { get; set; }
        public string urun_ad { get; set; }
        public string urun_ebat { get; set; }
        public Nullable<int> urun_hammadde_id { get; set; }
        public Nullable<int> urun_bakim_id { get; set; }
        public string urun_uretici { get; set; }
        public Nullable<decimal> urun_fiyat { get; set; }
        public string urun_kisa_aciklama { get; set; }
        public string urun_uzun_aciklama { get; set; }
        public string urun_teminat { get; set; }
        public Nullable<int> urun_stok { get; set; }
        public string urun_resim { get; set; }
    
        public virtual BAKIM BAKIM { get; set; }
        public virtual HAMMADDE HAMMADDE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEPET> SEPET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPARIS_K> SIPARIS_K { get; set; }
    }
}
