//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalSatisAgi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.SEPET = new HashSet<SEPET>();
            this.SIPARIS = new HashSet<SIPARIS>();
        }
    
        public int user_id { get; set; }
        public string user_ad { get; set; }
        public string user_soyad { get; set; }
        public string user_mail { get; set; }
        public string user_telefon { get; set; }
        public string user_sifre { get; set; }
        public Nullable<int> user_yetki_id { get; set; } = 3;
        public string user_adres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEPET> SEPET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPARIS> SIPARIS { get; set; }
        public virtual YETKI YETKI { get; set; }
    }
}
